language: cpp
sudo: required
dist: trusty
os:
- linux
env:
  - EXTRA_CXX_FLAGS -fprofile-arcs -ftest-coverage
notifications:
  email:
    - rebirthdb-dev@googlegroups.com
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install mg
  - sudo apt-get install build-essential protobuf-compiler python
  - sudo apt-get install libprotobuf-dev libcurl4-openssl-dev libboost-all-dev
  - sudo apt-get install libncurses5-dev libjemalloc-dev wget m4
  - pip install --user cpp-coveralls

# Compiler selection
compiler:
  - gcc

before_install:
  - pip install --user cpp-coveralls
  - export CXX_FLAGS="$CXX_FLAGS $EXTRA_CXX_FLAGS"

# Build steps
install:
  - ./configure CXXFLAGS="$CXX_FLAGS" --allow-fetch
  - make -j3 && make test -j3

script:
  - ./build/release/rethinkdb-unittest

after_success:
  - coveralls --gcov-options '\-lp'
