language: cpp
sudo: required
dist: trusty
os:
- linux
notifications:
  email:
    - rebirthdb-dev@googlegroups.com

matrix:
  include:
    # Enable C++ support
    - language: cpp
      before_install:
        - sudo apt-get -qq update
        - sudo apt-get install mg
        - sudo apt-get install build-essential protobuf-compiler python
        - sudo apt-get install libprotobuf-dev libcurl4-openssl-dev libboost-all-dev
        - sudo apt-get install libncurses5-dev libjemalloc-dev wget m4 g++

      # Compiler selection
      compiler:
        - gcc

      # Build steps
      install:
        - ./configure --allow-fetch
        - make -j8

      script:
        - make test
        - ./build/release/rethinkdb-unittest

    # Enable C++ support
    - language: cpp
      before_install:
        - sudo apt-get -qq update
        - sudo apt-get install mg
        - sudo apt-get install build-essential protobuf-compiler python
        - sudo apt-get install libprotobuf-dev libcurl4-openssl-dev libboost-all-dev
        - sudo apt-get install libncurses5-dev libjemalloc-dev wget m4 g++

      # Compiler selection
      compiler:
        - gcc

      # Build steps
      install:
        - ./configure --allow-fetch
        - make -j8

      script:
        - make test
        - ./build/release/rethinkdb-unittest
